package com.rzh.valo.ui.theme

import androidx.compose.ui.graphics.Color

// 品牌色（VALORANT 红）派生；Android 12+ 默认走动态取色
val BrandPrimary = Color(0xFFA3382F)
val BrandOnPrimary = Color(0xFFFFFFFF)
val BrandPrimaryContainer = Color(0xFFFFDAD5)
val BrandOnPrimaryContainer = Color(0xFF410002)
val BrandSecondaryContainer = Color(0xFFE8E0E8)
val BrandOnSecondaryContainer = Color(0xFF2B2029)
val BrandSecondary = Color(0xFF755653)
val BrandOnSecondary = Color(0xFFFFFFFF)
val BrandTertiary = Color(0xFF705C2E)
val BrandOnTertiary = Color(0xFFFFFFFF)
val BrandTertiaryContainer = Color(0xFFFBDFA6)
val BrandOnTertiaryContainer = Color(0xFF261A00)
val BrandSurface = Color(0xFFFFF8F6)
val BrandSurfaceVariant = Color(0xFFF5DDDA)
val BrandOutline = Color(0xFF857370)
val BrandOutlineVariant = Color(0xFFD8C2BE)

val BrandPrimaryDark = Color(0xFFFFB4A8)
val BrandOnPrimaryDark = Color(0xFF650E05)
val BrandPrimaryContainerDark = Color(0xFF86241C)
val BrandOnPrimaryContainerDark = Color(0xFFFFDAD5)
val BrandSecondaryContainerDark = Color(0xFF4A4249)
val BrandOnSecondaryContainerDark = Color(0xFFE8E0E8)
val BrandSecondaryDark = Color(0xFFE5BDB8)
val BrandOnSecondaryDark = Color(0xFF432A27)
val BrandTertiaryDark = Color(0xFFDEC48C)
val BrandOnTertiaryDark = Color(0xFF3E2E04)
val BrandTertiaryContainerDark = Color(0xFF574519)
val BrandOnTertiaryContainerDark = Color(0xFFFBDFA6)
val BrandSurfaceDark = Color(0xFF1A1110)
val BrandSurfaceVariantDark = Color(0xFF534341)
val BrandOutlineDark = Color(0xFFA08C88)
val BrandOutlineVariantDark = Color(0xFF534341)
